version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          filters:
              branches:
                  only:
                    - circleci
      - node/install-packages:
          cache-path: client/
          override-ci-command: npm install
          start: npm start
          record: true
